# Generated by Django 4.2.16 on 2025-03-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeEtab', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=10)),
                ('Genre', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('Niveau', models.CharField(max_length=50)),
                ('RetardSco', models.CharField(choices=[('0', '0 years'), ('1', '1 year'), ('2', '2 years')], max_length=1)),
                ('Provenance', models.CharField(max_length=50)),
                ('Handicap', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('Fee_reimbursement', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('CD_MIL', models.IntegerField()),
                ('Moy', models.FloatField()),
                ('Result', models.CharField(choices=[('Continue', 'Continue'), ('Drop', 'Drop'), ('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
