# Generated by Django 4.2.16 on 2025-03-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_inputdata_cd_mil_remove_inputdata_handicap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='Fee_reimbursement',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='Genre',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='Result',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='RetardSco',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='TypeEtab',
            field=models.CharField(max_length=10),
        ),
    ]
